# Forzar a Gradle Daemon a correr bajo JDK 17
org.gradle.java.home=/usr/lib/jvm/java-17-openjdk

# Optimización de compilación local
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# Habilitar soporte moderno de AndroidX
android.useAndroidX=true

# Silenciar aviso de compatibilidad con Android 15 (SDK 35)
android.suppressUnsupportedCompileSdk=35